# See https://hub.docker.com/u/drupalci

version: "3.5"

services:
  traefik:
    image: "traefik:v2.10"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - ash_entrypoint

networks:
  ash_entrypoint:
    name: proxy_network
